
CREATE TABLE `workers` (
  `WORKER_ID` varchar(6) NOT NULL DEFAULT '',
  `WORKER_NAME` varchar(40) DEFAULT NULL,
  `PLACE` varchar(35) DEFAULT NULL,
  `SALARY` decimal(10,2) DEFAULT NULL,
  `PHONE_NO` varchar(15) DEFAULT NULL,
  `BRANCH_ID` varchar(6) NOT NULL DEFAULT '',
  PRIMARY KEY (`WORKER_ID`),
  FOREIGN KEY (`BRANCH_ID`) REFERENCES branchID (`BRANCH_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


INSERT INTO `agents` (`WORKER_ID`, `WORKER_NAME`, `PLACE`, `SALARY`, `PHONE_NO`, `BRANCH_ID`) VALUES
("WORKER_ID", "WORKER_NAME", "PLACE", "SALARY", "PHONE_NO", "BRANCH_ID"),
("WORKER_ID", "WORKER_NAME", "PLACE", "SALARY", "PHONE_NO", "BRANCH_ID");
